"""question table migration.

Revision ID: 813e9f25be18
Revises: ef660f2579b7
Create Date: 2023-07-16 12:13:48.844489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '813e9f25be18'
down_revision = 'ef660f2579b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sqlite.JSON(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
