"""exams & question tables migration.

Revision ID: bf45b307a03a
Revises: a59610150838
Create Date: 2023-07-20 19:47:40.828188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf45b307a03a'
down_revision = 'a59610150838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_mounted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('author', 'user', ['author'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_mounted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
