"""question table migration.

Revision ID: ef660f2579b7
Revises: 8eb4e152a441
Create Date: 2023-07-16 11:45:53.951568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef660f2579b7'
down_revision = '8eb4e152a441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('answer',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
